openapi: 3.0.0
info:
  title: Simple User API
  version: 1.0.0
servers:
  - url: https://api.example.com/v1
paths:
  /books/{id}/reviews:
    get:
      summary: Get reviews for a book
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: A list of reviews
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Review'
components:
  schemas:
    Review:
      type: object
      properties:
        id:
          type: string
        content:
          type: string
        rating:
          type: integer
